name: quicknxs
channels:
    - conda-forge
    - neutrons
    - default
    - mantid
    - mantid/label/nightly
dependencies:
- python=3.8
- matplotlib>=3.6
- mantid>=6.4
- codecov
- conda-build
- conda-verify
- pylint
- pytest
- pytest-qt
- pytest-cov
- pytest-xvfb
- build
- toml
- pip:
    - versioningit
    - check-wheel-contents
